#!/usr/bin/env python3
"""
dnshub-privacy - local encrypted DNS front: DoT on :853 and DoH on :443.

Purpose: the last leg. LAN/Wi-Fi sniffers and the VPN path itself can see
plain DNS unless the *device-to-box* hop is encrypted. This service terminates
TLS (a CA the user controls, generated by `dnshub install`) and forwards the
wire query to the dnshub resolver on 127.0.0.1:53 and nothing else. There is
no other upstream here, so the "encrypted all the way" property is enforced
by construction: no plaintext fallback exists in this file.

Routes (DoH):
  GET/POST /dns-query   application/dns-message -> resolver
  GET /ca.pem           install this CA once on each device
  GET /                 tiny setup page

DoT is a 2-byte length-prefixed DNS-over-TLS stream with ALPN "dot",
compatible with Android Private DNS, iOS profiles, stubby, kdig, etc.
"""
from __future__ import annotations

import asyncio
import base64
import contextlib
import os
import socket
import ssl
import struct
import sys
import time
import urllib.parse
from pathlib import Path

CERT = Path(os.environ.get("DNSHUB_PRIV_CERT", "/etc/dnshub/certs/server.crt"))
KEY = Path(os.environ.get("DNSHUB_PRIV_KEY", "/etc/dnshub/certs/server.key"))
CA = Path(os.environ.get("DNSHUB_PRIV_CA", "/etc/dnshub/certs/ca.crt"))
RESOLVER = (os.environ.get("DNSHUB_PRIV_UPSTREAM", "127.0.0.1"), 53)
QUERY_BUDGET = float(os.environ.get("DNSHUB_PRIV_TIMEOUT", "4"))
MAX_DNS = 4096  # largest single DNS message we accept (EDNS0 stays well under)

_conns = 0


def log(msg: str) -> None:
    sys.stdout.write(f"[{time.strftime('%H:%M:%S')}] privacy: {msg}\n")
    sys.stdout.flush()


# --- resolver hop -----------------------------------------------------------
def _udp_query(wire: bytes) -> bytes | None:
    """One shot at the local resolver over UDP. Blocking, short, called from
    the executor so the event loop is never held."""
    s = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
    s.settimeout(QUERY_BUDGET)
    try:
        s.sendto(wire, RESOLVER)
        data, _ = s.recvfrom(65535)
        return data
    except OSError:
        return None
    finally:
        s.close()


async def forward(wire: bytes) -> bytes | None:
    loop = asyncio.get_event_loop()
    return await loop.run_in_executor(None, _udp_query, wire)


def servfail(wire: bytes) -> bytes:
    """Minimal SERVFAIL that reuses the client's id and question when safe."""
    try:
        import dns.message
        q = dns.message.from_wire(wire, ignore_trailing=True)
        r = dns.message.make_response(q)
        r.set_rcode(dns.rcode.SERVFAIL)
        return r.to_wire()
    except Exception:
        # can't parse the question: a bare header-only SERVFAIL still lets a
        # client see the failure instead of hanging.
        return b"\x00\x00" + struct.pack(">H", 2) + b"\x00\x00\x00\x00\x00\x00"


def _check_certs() -> str | None:
    for p in (CERT, KEY, CA):
        if not p.is_file():
            return f"missing {p} (run `sudo dnshub install` to generate certs)"
    return None


def ssl_ctx(proto: str) -> ssl.SSLContext:
    ctx = ssl.SSLContext(ssl.PROTOCOL_TLS_SERVER)
    ctx.load_cert_chain(CERT, KEY)
    ctx.set_alpn_protocols([proto])
    ctx.minimum_version = ssl.TLSVersion.TLSv1_2
    return ctx


# --- DoT (RFC 7858) ----------------------------------------------------------
async def handle_dot(reader, writer) -> None:
    global _conns
    peer = writer.get_extra_info("peername")
    peer = peer[0] if peer else "?"
    _conns += 1
    with contextlib.suppress(Exception):
        not_al = (writer.get_extra_info("ssl_object").selected_alpn_protocol()
                  or "none")
        log(f"dot: {peer} connected (alpn={not_al})")
    try:
        while True:
            hdr = await reader.readexactly(2)
            (ln,) = struct.unpack(">H", hdr)
            if ln == 0 or ln > MAX_DNS:
                break
            wire = await reader.readexactly(ln)
            resp = await forward(wire)
            if resp is None:
                resp = servfail(wire)
                log(f"dot: resolver unreachable for {peer}, sent SERVFAIL")
            # mirror the response id to the client's request id if the resolver
            # changed it (it cannot - 127.0.0.1 echoes - but be defensive)
            writer.write(struct.pack(">H", len(resp)) + resp)
            await writer.drain()
    except (asyncio.IncompleteReadError, ConnectionResetError, BrokenPipeError,
            TimeoutError):
        pass
    except asyncio.CancelledError:
        pass
    except Exception as exc:
        log(f"dot: {peer} error: {type(exc).__name__}: {exc}")
    finally:
        with contextlib.suppress(Exception):
            writer.close()
            await writer.wait_closed()


# --- DoH (RFC 8484) ----------------------------------------------------------
async def _respond(writer, status, ctype, body: bytes) -> None:
    head = (f"HTTP/1.1 {status}\r\n"
            f"Content-Type: {ctype}\r\n"
            f"Content-Length: {len(body)}\r\n"
            f"Connection: close\r\n"
            f"Cache-Control: no-store\r\n\r\n")
    writer.write(head.encode() + body)
    await writer.drain()


PAGE = """<!doctype html><html><head><meta charset=utf-8>
<title>dnshub private DNS · by Mostfa</title><style>
body{background:#0d1117;color:#c9d1d9;font:14px/1.6 -apple-system,Segoe UI,Roboto,sans-serif;
 max-width:820px;margin:3rem auto;padding:0 18px}
h1{color:#58a6ff;font-size:20px}code{background:#161b22;border:1px solid #30363d;
 padding:2px 6px;border-radius:5px;color:#7ee787}
h2{color:#c9d1d9;font-size:15px;margin-top:2rem}
li{margin:.35rem 0}</style></head><body>
<h1>dnshub — مشفر DNS محلي (DoT :853 / DoH :443)</h1>
<p>كل طلب DNS بيوصل للسيرفر مشفر بثقة CA بتاعتك. ثبّت الـ CA مرة واحدة:</p>
<ul><li><a href="/ca.pem"><code>download /ca.pem</code></a> — ثبّته في مخزن الثقة بتاع الجهاز</li></ul>
<h2>Android — Private DNS</h2>
<ul><li>الهدف: <code>dns.home</code> (أو <code>192.168.1.12</code> لو الجهاز واقع على الشبكة)</li>
<li>لو خارج الشبكة وبالـ VPN: <code>10.8.0.1</code></li></ul>
<h2>Windows 11 — DoH بالإنترنت</h2>
<ul><li>Enable Private DNS (DoH) → <code>https://dns.home/dns-query</code></li>
<li>الشهادة محتاجة CA تكون مركّبة في <code>Trusted Root</code></li></ul>
<h2>iOS / macOS</h2>
<ul><li>ثبّت الـ CA بروفايل + profile DNS-over-TLS مع hostname <code>dns.home</code></li></ul>
<h2>kdig / stubby / dig</h2>
<code>kdig @dns.home -d google.com</code><br>
<code>curl --cacert /etc/dnshub/certs/ca.crt -H 'Accept: application/dns-message' \\
  --data-binary @q.bin https://dns.home/dns-query</code>
<footer style="margin-top:2.5rem;color:#6e7681;font-size:12px">dnshub v2.0 · built by Mostfa</footer>
</body></html>"""


async def handle_doh(reader, writer) -> None:
    peer = writer.get_extra_info("peername")
    peer = peer[0] if peer else "?"
    try:
        head = b""
        while b"\r\n\r\n" not in head and len(head) < 16384:
            chunk = await reader.read(4096)
            if not chunk:
                break
            head += chunk
        if b"\r\n\r\n" not in head:
            await _respond(writer, "400 Bad Request", "text/plain", b"bad request\n")
            return
        raw, _, rest = head.partition(b"\r\n\r\n")
        try:
            head_txt = raw.decode("ascii", "replace")
            req_line, *hlines = head_txt.split("\r\n")
            method, target, _ = req_line.split(" ", 2)
        except ValueError:
            await _respond(writer, "400 Bad Request", "text/plain", b"bad request\n")
            return
        headers = {}
        for h in hlines:
            if ":" in h:
                k, v = h.split(":", 1)
                headers[k.strip().lower()] = v.strip()

        if "expect" in headers and "100-continue" in headers["expect"].lower():
            writer.write(b"HTTP/1.1 100 Continue\r\n\r\n")
            await writer.drain()
            rest = b""

        parsed = urllib.parse.urlsplit(target)
        path = parsed.path
        if path == "/ca.pem" and method == "GET":
            body = CA.read_bytes()
            await _respond(writer, "200 OK", "application/x-pem-file", body)
            return
        if path == "/" and method == "GET":
            body = PAGE.encode()
            await _respond(writer, "200 OK", "text/html; charset=utf-8", body)
            return
        if path != "/dns-query":
            await _respond(writer, "404 Not Found", "text/plain", b"not found\n")
            return

        wire = b""
        if method == "GET":
            q = urllib.parse.parse_qs(parsed.query)
            enc = (q.get("dns") or [""])[0]
            if enc:
                enc += "=" * (-len(enc) % 4)
                with contextlib.suppress(Exception):
                    wire = base64.urlsafe_b64decode(enc)
        elif method == "POST":
            try:
                ln = int(headers.get("content-length", "0") or "0")
            except ValueError:
                ln = 0
            if ln > MAX_DNS:
                await _respond(writer, "413 Payload Too Large", "text/plain",
                               b"too large\n")
                return
            wire = rest
            while len(wire) < ln:
                chunk = await reader.read(min(4096, ln - len(wire)))
                if not chunk:
                    break
                wire += chunk

        if not wire:
            await _respond(writer, "400 Bad Request", "text/plain", b"empty query\n")
            return
        resp = await forward(wire)
        if resp is None:
            log(f"doh: resolver unreachable for {peer}")
            await _respond(writer, "502 Bad Gateway", "text/plain",
                           b"resolver down\n")
            return
        # honour the wire:id of the *client's* message if the resolver changed
        # it; RFC 8484 wants the response id preserved.
        await _respond(writer, "200 OK", "application/dns-message", resp)
    except (asyncio.CancelledError, ConnectionResetError):
        pass
    except Exception as exc:
        log(f"doh: {peer} error: {type(exc).__name__}: {exc}")
        with contextlib.suppress(Exception):
            await _respond(writer, "500 Internal Server Error", "text/plain",
                           b"error\n")
    finally:
        with contextlib.suppress(Exception):
            writer.close()
            await writer.wait_closed()


async def main() -> int:
    err = _check_certs()
    if err:
        log(err)
        return 1
    dot_ctx = ssl_ctx("dot")
    doh_ctx = ssl_ctx("http/1.1")
    d1 = await asyncio.start_server(handle_dot, "0.0.0.0", 853, ssl=dot_ctx)
    d2 = await asyncio.start_server(handle_doh, "0.0.0.0", 443, ssl=doh_ctx)
    log(f"dot :853  doh :443  upstream={RESOLVER[0]}:{RESOLVER[1]}")
    async with d1, d2:
        await asyncio.gather(d1.serve_forever(), d2.serve_forever())
    return 0


if __name__ == "__main__":
    try:
        sys.exit(asyncio.run(main()))
    except KeyboardInterrupt:
        sys.exit(130)